[tool.poetry]
name = "teleop"
version = "0.1.0"
description = ""
authors = ["Karthik <kkarthikm35@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
